# Generated by Django 4.0.5 on 2022-06-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_destruct_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='destruct_timer',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
