# Generated by Django 4.0.5 on 2022-06-10 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_alter_message_destruct_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='friends',
            field=models.ManyToManyField(related_name='user_friends', related_query_name='users_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
