# Generated by Django 4.0.5 on 2022-06-10 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_friendlist_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendlist',
            old_name='friends',
            new_name='friend',
        ),
    ]
