# Generated by Django 4.0.5 on 2022-06-10 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_rename_friends_friendlist_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='friend',
            field=models.ManyToManyField(related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
