# Generated by Django 4.0.5 on 2022-06-10 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_alter_friendlist_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(related_name='user_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
